# README

https://github.com/tongweizj/experiments_Machine-Learning/issues/13

In [2]:
import torch

## 基本事例
使用 computational graph
- `requires_grad=True`：启用追踪
- `.backward()`：触发梯度计算
- `.grad`：访问梯度值

In [3]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1
y.backward()
print(x.grad)  # dy/dx = 2x + 3

tensor(7.)


In [ ]:


x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [2]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x77a2cb7d96c0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x77a2cb7da020>


In [3]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0398, 0.0033, 0.0781],
        [0.0398, 0.0033, 0.0781],
        [0.0398, 0.0033, 0.0781],
        [0.0398, 0.0033, 0.0781],
        [0.0398, 0.0033, 0.0781]])
tensor([0.0398, 0.0033, 0.0781])


## 多步张量运算

In [7]:
a = torch.randn(3, requires_grad=True)
print(a)
print(a.grad)
b = a * 2
print(b)
print(a.grad)
c = b.mean()
print(c)
print(a.grad)
c.backward()
print(a.grad)

tensor([-0.1480, -0.5153,  1.5880], requires_grad=True)
None
tensor([-0.2959, -1.0305,  3.1760], grad_fn=<MulBackward0>)
None
tensor(0.6165, grad_fn=<MeanBackward0>)
None
tensor([0.6667, 0.6667, 0.6667])


## 画图

In [ ]:
import torch
import matplotlib.pyplot as plt
import numpy as np