# Readme

This script is from https://www.tensorflow.org/tutorials/quickstart/beginner
I add function api code block.

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


## Model 构建
下面使用了两种方法构建模型！
Sequential 和 function api
通过summary 观察他们的结构，会发现是一致的！

In [ ]:
# Sequential
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

model.summary()

In [ ]:
# function api
inputs = keras.Input(shape=(28, 28))
x = keras.layers.Flatten()(inputs)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)
outputs = keras.layers.Dense(10, activation='softmax')(x)
model-function-api = keras.Model(inputs=inputs, outputs=outputs)

model-function-api.summary()

模型测试
用一行数据去测试模型设计是否存在问题
这个办法是对的

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.05291419, 0.09906553, 0.14255054, 0.10105634, 0.05500812,
        0.05896794, 0.08120553, 0.10817958, 0.16499242, 0.13605976]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.09533512, 0.09983808, 0.10427532, 0.10003704, 0.09553496,
        0.09591401, 0.09807079, 0.10075217, 0.1066419 , 0.10360067]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.11/dist-packages/keras/src/backend/tensorflow/nn.py:708: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8612 - loss: 0.4830
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9583 - loss: 0.1476
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9685 - loss: 0.1039
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 7ms/step - accuracy: 0.9734 - loss: 0.0847
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9774 - loss: 0.0722


In [12]:
model.evaluate(x_test,  y_test, verbose=2)
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

313/313 - 1s - 2ms/step - accuracy: 0.9769 - loss: 0.0763


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08534149, 0.08534143, 0.08534178, 0.08537223, 0.08534143,
        0.08534153, 0.08534143, 0.23189527, 0.08534145, 0.08534203],
       [0.08534731, 0.08536788, 0.23180224, 0.08539549, 0.0853473 ,
        0.0853475 , 0.08534731, 0.0853473 , 0.08535041, 0.0853473 ],
       [0.08537151, 0.23141892, 0.08543431, 0.08538131, 0.0853952 ,
        0.08537217, 0.08537323, 0.08548178, 0.08539998, 0.08537165],
       [0.23196459, 0.08533704, 0.08533753, 0.08533704, 0.08533811,
        0.08533707, 0.08533709, 0.08533748, 0.08533704, 0.08533707],
       [0.08534703, 0.08534532, 0.08534646, 0.08534532, 0.23183371,
        0.08534532, 0.0853456 , 0.08534648, 0.08534578, 0.08539904]],
      dtype=float32)>